[phases.setup]
    packages = ["python38", "gcc"]
    commands = [
        "python -m venv .venv",
        ". /.venv/Scripts/activate",
        "pip install -r requirements.txt"
    ]

[phases.build]
    commands = ["echo 'Build step not required for this application.'"]

[phases.start]
    commands = [". /.venv/Scripts/activate && gunicorn -w 4 src.app:app"]
