[phases.setup]
    packages = ["python38", "gcc"]
    commands = [
        "python -m venv /opt/venv",
        ". /opt/venv/bin/activate",
        "pip install -r requirements.txt"
    ]

[phases.build]
    commands = ["echo 'Build step not required for this application.'"]

