[phases.setup]
    packages = ["python38", "gcc"]
    commands = [
        "python -m venv --copies /opt/venv",
        ". /opt/venv/bin/activate",
        "pip install -r requirements.txt"
    ]

[phases.build]
    commands = ["echo 'Build step not required for this application.'"]

[phases.start]
    commands = [". /opt/venv/bin/activate &amp;&amp; gunicorn -w 4 src.app:app"]